### ISSUE TITLE
QMessageBox for error

### ISSUE THREAD

**Issue by codenoid** [Muonyet/lazy-mongo#3]

**Comment by codenoid** [comment]
cc @Papierkorb , i can't find Qt::QMessageBox in qt5 binding

**Comment by Papierkorb** [comment]
Add the necessary class(es) to `classes.yml` and enum(s) to `enums.yml` (Both in `config/`).  Then run bindgen as documented in Qt5.cr's README to verify (The section on how to generate a single version).  Once it works PR it so it can go upstream.
